name: Flask app tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    env:
      HBNB_API_PORT: ${{ secrets.HBNB_API_PORT }}
      HBNB_API_HOST: ${{ secrets.HBNB_API_HOST }}
      HBNB_TYPE_STORAGE: ${{ secrets.HBNB_TYPE_STORAGE }}
      HBNB_MYSQL_DB: ${{ secrets.HBNB_MYSQL_DB }}
      HBNB_MYSQL_HOST: ${{ secrets.HBNB_MYSQL_HOST }}
      HBNB_MYSQL_USER: ${{ secrets.HBNB_MYSQL_USER }}
      HBNB_MYSQL_PWD: ${{ secrets.HBNB_MYSQL_PWD }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: List files
        run: ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./AirBnB_clone_v3

      - name: Test App code
        run: python3 app/api/v1/app.py
        working-directory: ../
